# Generated by Django 5.2.14 on 2026-05-06 22:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'estado_reserva',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField()),
                ('capacidad_maxima', models.PositiveSmallIntegerField()),
                ('precio_por_noche', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('mantenimiento', 'Mantenimiento'), ('inactiva', 'Inactiva')], default='disponible', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'habitacion',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'metodo_pago',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'servicio',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('capacidad_base', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'tipo_habitacion',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dpi', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='DPI')),
                ('telefono', models.CharField(max_length=25)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cliente',
                'ordering': ['apellido', 'nombre'],
                'indexes': [models.Index(fields=['apellido', 'nombre'], name='idx_cliente_nombre'), models.Index(fields=['telefono'], name='idx_cliente_telefono'), models.Index(fields=['correo'], name='idx_cliente_correo')],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_reserva', models.CharField(blank=True, max_length=30, unique=True)),
                ('fecha_entrada', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('cantidad_personas', models.PositiveSmallIntegerField()),
                ('total_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='reservas.cliente')),
                ('estado_reserva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='reservas.estadoreserva')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='reservas.habitacion')),
            ],
            options={
                'db_table': 'reserva',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_recibido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cambio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='reservas.metodopago')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='reservas.reserva')),
            ],
            options={
                'db_table': 'pago',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField()),
                ('aprobado', models.BooleanField(default=False)),
                ('fecha_comentario', models.DateTimeField(auto_now_add=True)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='comentario', to='reservas.reserva')),
            ],
            options={
                'db_table': 'comentario_habitacion',
                'ordering': ['-fecha_comentario'],
            },
        ),
        migrations.CreateModel(
            name='HabitacionServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.habitacion')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservas.servicio')),
            ],
            options={
                'db_table': 'habitacion_servicio',
            },
        ),
        migrations.AddField(
            model_name='habitacion',
            name='servicios',
            field=models.ManyToManyField(blank=True, related_name='habitaciones', through='reservas.HabitacionServicio', to='reservas.servicio'),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='tipo_habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='habitaciones', to='reservas.tipohabitacion'),
        ),
        migrations.CreateModel(
            name='ImagenHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='habitaciones/')),
                ('descripcion', models.CharField(blank=True, max_length=150)),
                ('es_principal', models.BooleanField(default=False)),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='reservas.habitacion')),
            ],
            options={
                'db_table': 'imagen_habitacion',
                'ordering': ['orden', 'id'],
                'indexes': [models.Index(fields=['habitacion', 'es_principal'], name='idx_img_principal')],
            },
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['codigo_reserva'], name='idx_res_codigo'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['fecha_entrada'], name='idx_res_entrada'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['fecha_salida'], name='idx_res_salida'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['estado_reserva'], name='idx_res_estado'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['habitacion', 'fecha_entrada', 'fecha_salida'], name='idx_res_hab_fechas'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['reserva'], name='idx_pago_reserva'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['metodo_pago'], name='idx_pago_metodo'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['fecha_pago'], name='idx_pago_fecha'),
        ),
        migrations.AddIndex(
            model_name='comentariohabitacion',
            index=models.Index(fields=['aprobado'], name='idx_com_aprobado'),
        ),
        migrations.AddIndex(
            model_name='comentariohabitacion',
            index=models.Index(fields=['puntuacion'], name='idx_com_puntuacion'),
        ),
        migrations.AddConstraint(
            model_name='habitacionservicio',
            constraint=models.UniqueConstraint(fields=('habitacion', 'servicio'), name='uq_habitacion_servicio'),
        ),
        migrations.AddIndex(
            model_name='habitacion',
            index=models.Index(fields=['tipo_habitacion'], name='idx_hab_tipo'),
        ),
        migrations.AddIndex(
            model_name='habitacion',
            index=models.Index(fields=['estado'], name='idx_hab_estado'),
        ),
        migrations.AddIndex(
            model_name='habitacion',
            index=models.Index(fields=['capacidad_maxima'], name='idx_hab_capacidad'),
        ),
        migrations.AddIndex(
            model_name='habitacion',
            index=models.Index(fields=['precio_por_noche'], name='idx_hab_precio'),
        ),
    ]
